version: '3'

services:
  db:
    image: postgres
  backend:
    build: 
        context: .
        dockerfile: ./django/Dockerfile
    command: python3 ./django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: 
        context: .
        dockerfile: ./vue/Dockerfile
    command: echo "ready"
    volumes:
      - .:/frontend
    ports:
      - 3000:3000
    depends_on:
      - db
      - backend