version: '3'

services:
  db:
    image: postgres
  backend:
    build: 
        context: .
        dockerfile: ./django/Dockerfile
    #command: python3 ./django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    entrypoint: ["bash","django-entrypoint.sh"]
    depends_on:
      - db
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
    #command: npm start
    volumes:
      - '.:/frontend'
      - './frontend/node_modules'
    ports:
      - 3000:3000
    entrypoint: ["bash","react-entrypoint.sh"]
    depends_on:
      - db
      - backend